### PR TITLE
Allow cookie-0.5

### PR DESCRIPTION
**Pull request by spencerjanssen**

### CODE REVIEW

**Comment by phadej** [comment]
The changelog for `cookie-0.5` says

> This is a breaking change, as it changes the behavior of parseCookies and parseSetCookie to no longer include the surrounding double quotes in the cookie value. This is the correct behavior according to the RFC.

And we do use `parseSetCookie`. Have you verified that things still work?

**Comment by spencerjanssen** [comment]
I did run the test suite, yes. Reasonable uses of the API provided by `cookie` or `http-api-data` will not break. According to the RFC user agents may *optionally* wrap the cookie value in double quotes.

I think we are also covered by the disclaimer attached to the instances for `SetCookie`:

> `/Note:/ this instance works correctly for alphanumeric name and value`

I can add a note about this in the changelog if you'd like.

**Comment by spencerjanssen** [comment]
Sounds good. I can add a changelog entry. Shall I include a minor version bump up to 0.6.1 as well?

**Comment by phadej** [comment]
> Shall I include a minor version bump up to 0.6.1 as well?

Please do.

**Comment by spencerjanssen** [comment]
Done, thanks for the review!

**Pull request closed without merging**
