### PR TITLE
Add Semigroup Form instance

### PR DESCRIPTION
**Pull request by RyanGlScott**
This is needed to fix the build on GHC 8.4, where `Semigroup` is now a superclass of `Monoid`.

This declares a dependency on `semigroups`, but `http-api-data` was already transitively depending on `semigroups` via `attoparsec`.

### CODE REVIEW

**Comment by phadej** [comment]
Attoparsec (and IIRC all other deps) have GHC-conditional dependency on semigroups: https://hackage.haskell.org/package/attoparsec-0.13.2.2/dependencies

**Comment by RyanGlScott** [comment]
OK. Should I interpret that statement as "please change the `semigroups` dependency in `http-api-data.cabal` to be conditional as well"?

**Comment by phadej** [comment]
And we need to bump lower bound on unordered containers, don't we? https://hackage.haskell.org/package/unordered-containers-0.2.8.0/changelog

**Comment by RyanGlScott** [comment]
...erm, I don't know? I'm not affiliated with `unordered-containers` in any way.

**Comment by RyanGlScott** [comment]
After getting some sleep, I realize that I might have wildly misinterpreted https://github.com/fizruk/http-api-data/pull/68#issuecomment-362958815. I believe what you're asking is for me to change `http-api-data.cabal` such that:

* The dependency on `semigroups` is conditional on `if !impl(ghc >= 8.0)`.
* The lower version bounds for `unordered-containers` is `0.2.6`.

Can you confirm if this is correct?

**Comment by phadej** [comment]
@RyanGlScott yes! sorry for being cryptic myself, I hadn't enough sleep myself!

**Comment by RyanGlScott** [comment]
Hm, the build is apparently failing due to this line:

https://github.com/fizruk/http-api-data/blob/b61b1525a7cffb5cde93a080a991427a74cf5489/.travis.yml#L109

which hardcodes a version number for `unordered-containers` that is older than 2.6.0. Is there a particular motivation for using this version number?

**Comment by phadej** [comment]
@RyanGlScott yes, I want to check lowerbounds, and seems I have to check them on newer GHCs too, as that check didn't catch incorrect lowerbound (as lowerbounds were tested only on GHC-7.8.4 and GHC-7.10.3)

**Comment by RyanGlScott** [comment]
OK, I'll try changing those lower bounds to `0.2.6.0`.

**Comment by RyanGlScott** [comment]
...oops, I just noticed that this may be superseded by https://github.com/fizruk/http-api-data/pull/69 now.

**Comment by phadej** [comment]
Sorry for not notifying, merged as part of #69

**Pull request closed without merging**
