### PR TITLE
Ghc 8.4.1

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
blocked on blaze-builder

**Comment by DanBurton** [comment]
blaze-builder-0.4.1.0 has been released, which should unblock this. A prompt release would be much appreciated, as I'd love to get this into the next Stackage nightly!

**Comment by phadej** [comment]
@DanBurton thanks for pinging

**Comment by DanBurton** [comment]
I have observed passing tests from the latest commit on this PR, like so:

```bash
stack upgrade --git --git-branch stable
git clone https://github.com/phadej/http-api-data
cd http-api-data/
git checkout 1f8ef4fb381d7bfa5ede6e6752b4bf97b1701904
edit stack-ghc-8-2.yaml # add the following yaml file
stack --stack-yaml stack-ghc-8-4.yaml test
```

```yaml
resolver: nightly-2018-03-14

packages:
- '.'

flags:
  http-api-data:
    use-text-show: false

extra-deps:
- uri-bytestring-0.3.1.1
- blaze-builder-0.4.1.0
- quickcheck-instances-0.3.18
- uuid-1.3.13
- doctest-0.14.1
- cryptohash-md5-0.11.100.1
- cryptohash-sha1-0.11.100.1
- entropy-0.3.8
- network-info-0.2.0.9

allow-newer: true

extra-package-dbs: []
```

Unfortunately, `allow-newer: true` was necessary in order to convince the following bounds to be ignored:

```
WARNING: Ignoring out of range dependency (allow-newer enabled): base-4.11.0.0. cryptohash-md5 requires: >=4.5 && <4.11
WARNING: Ignoring out of range dependency (allow-newer enabled): base-4.11.0.0. cryptohash-sha1 requires: >=4.5 && <4.11
WARNING: Ignoring out of range dependency (allow-newer enabled): Cabal-2.2.0.0. entropy requires: >=1.10 && <2.2
```

Note, however, that these particular dependencies were only necessary for testing, and not for the package itself. I am explaining this in order to lend confidence to merging and releasing this PR, despite difficulties you may encounter while testing it (since `uuid`'s deps remain overconstrained for ghc-8.4.1).

Also note that you could relax your constraint on `doctest` to `< 0.16`, as the same passing tests can be observed with `doctest-0.15.0`.

**Comment by phadej** [comment]
@DanBurton thanks for mentioning doctest-0.15, I'd forgot that otherwise.

**Comment by phadej** [comment]
For the record: there is install plan without cryptohash-* and entropy, they were unnecessarily pulled by `uuid` (we are good with `uuid-types` only)

**Comment by phadej** [comment]
released as https://hackage.haskell.org/package/http-api-data-0.3.8.1

**Pull request merged**
