### PR TITLE
Uuid

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Seems that instances in `quickcheck-instances` generate subseconds. Either we could use `checkUrlPiece'` or own equality.

**Comment by fizruk** [comment]
There was an issue on `UUID` before — #21. @gregwebs had some points to not have `uuid` dependency here.

**Comment by phadej** [comment]
bummer. `uuid` is an extremely light dependency.
So far it's 2-1 for having `uuid` (assuming @fizruk is :+1: and @gregwebs is :-1:). 

Continuing from #21, `cuid` is nice too, and  it's instances could be here too, but when interoperating with java-world apps, not having UUIDs is no go.

**Comment by phadej** [comment]
FWIW, I'll redo this PR with depending only [`uuid-types`](http://hackage.haskell.org/package/uuid-types) which is indeed much lighter than `uuid`

**Pull request merged**
