### PR TITLE
correct time-locale-compat bounds

### PR DESCRIPTION
**Pull request by phadej**
See edits thru http://matrix.hackage.haskell.org/package/http-api-data

### CODE REVIEW

**Comment by phadej** [comment]
Don't work on older base because
```
Module `Text.Read' does not export `readMaybe'
```

**Comment by fizruk** [comment]
@phadej I guess we could use `base-compat` for that?

**Comment by phadej** [comment]
If you like, but that would be the code change. Feel free to use it of course.

**Comment by fizruk** [comment]
@phadej you mean the other alternative being to fix `base` version bounds?

I am not sure anyone is using GHC <7.6, so maybe we should just cut it off?
I honestly don't know what's the right action here.

**Comment by phadej** [comment]
@fizruk yes, `base >=4.6` is good alternative. If someone would need support for older, providing it would be easy. But as it's not the goal atm let's not lie in version bounds.

**Comment by phadej** [comment]
Also no new release is needed, as I corrected bounds on the Hackage. This is kind of "backporting" PR.

**Comment by fizruk** [comment]
Ah, great! I didn't realise it was possible to change version bounds after the fact!

**Comment by phadej** [comment]
bump

**Comment by fizruk** [comment]
@phadej should I make a release with these changes? Or update `.cabal` file on Hackage?

**Comment by phadej** [comment]
@fizruk I corrected all bounds on Hackage, no action required atm. The PR was just to prevent new "actual" releases from having incorrect bounds too.

Everything is fine. :+1:

**Comment by fizruk** [comment]
@phadej nice, thanks!

**Pull request merged**
