### PR TITLE
From/ToFormUrlEncoded (Do not merge)

### LINKED ISSUE #23: Bring To/FromFormUrlEncoded from servant
Probably with a generic deriving mechanism for records, whose fields have `To/FromHttpApiData` instances.

### PR DESCRIPTION
**Pull request by jkarni**
Fixes #23. This isn't ready yet. Some questions:

- It turns out `To/FromFormUrlEncoded` don't actually expect/return url-encoded forms. Encoding and decoding happens before/after. To me this means their names should be changed to `To/FromForm`, but I wanted to see what others thought.
- I imagine using `to/parseQueryParam` in the generic instance is more correct than `to/parseUrlPiece`?
- The generic instance returns the underlying parse error, but not yet the key for which parsing failed. I would say doing that could be done in a separate PR. It involves changing the signature of `gFromForm` though, and maybe that shouldn't be considered internal.
- I'm not very familiar with `GHC.Generics` and generic programming, so there may be issues here.
- There should probably eventually be an `options` for the generic stuff. 

I still need to check sum record types, squash some commits, and move the tests for encoding/decoding over.

### CODE REVIEW

**Comment by cdepillabout** [comment]
I guess this PR has bee stalled for a while, but is there anything I can do to help push it along?

I've wanted something like this for the last couple months, and I finally [created an issue](https://github.com/haskell-servant/servant/issues/575) about it over on the servant repository, but I didn't realize it was already being worked on!

**Comment by jkarni** [comment]
@cdepillabout I just finished up some more tests, squashed, and cleaned up a little. Do you want to try rebasing against master? It's a pretty ugly merge/rebase!

**Comment by jkarni** [comment]
Relatedly, while moving the encoding and decoding functions over I noticed that they seem to be doing much more converting between String, ByteString and Text than is healthy. At some point we should try to improve on that.

**Comment by cdepillabout** [comment]
@jkarni Sure, I'll do the rebase onto master.  You might have to give a few days though.

**Comment by cdepillabout** [comment]
@jkarni: I've rebased your code onto master.  You can find the updated code here:

https://github.com/fizruk/http-api-data/pull/31

**Comment by jkarni** [comment]
This too has been superseded by #32

**Pull request closed without merging**
