### PR TITLE
Ghc 8.2

### LINKED ISSUE #43: Build failure with GHC HEAD
```
[1 of 1] Compiling Main             ( Setup.lhs, /tmp/nix-build-http-api-data-0.2.4.drv-0/Main.o )

Setup.lhs:7:31: error:
    Module
    ‘Distribution.Package’
    does not export
    ‘PackageName(PackageName)’
```

### PR DESCRIPTION
**Pull request by phadej**
(will) resolve #43 (and #42).

### CODE REVIEW

**Comment by phadej** [comment]
This is directly based on https://github.com/ekmett/bytes/pull/32 with small additions.

I can revert `.travis.yml` to the `HEAD` state (and use stack). But I like this setup.

Also for the record: 0.3 version uses closed type families, so GHC >= 7.8 is hard requirement.

**Comment by fizruk** [comment]
@phadej you now have write access to this repository.

**Comment by phadej** [comment]
I'm still experimenting with making `setup.lhs` and `doctests.hsc` copy&pasteable across wider set of packages. It starts to look good already.

**Comment by phadej** [comment]
Thanks for the rights!

So you are ok with not testing `stack.yaml` in Travis? (then it might make sense to use only single one, for the dev)

**Comment by phadej** [comment]
Sorry for the spam. But I'd wait with this until Ben & Ryan are commented on this (in other repos PR, `distributive`), before continuing with this.

I'm also not 100% sure that non-released Cabal api won't change, but I guess it's still ok to push this to Hackage as `setup-depends` are in place.

**Comment by fizruk** [comment]
@phadej where's the discussion this is blocked on?

**Comment by phadej** [comment]
I pushed a commit, if it's green with 8.2, than feel free to merge

**Comment by fizruk** [comment]
Great! Thanks!

**Pull request merged**
